# Required Library

In [18]:
!pip install sqlalchemy pymysql

Access is denied.

In [2]:
# !pip install openpyxl

In [1]:
# Libraries
import pandas as pd
input_folder_path = "DataSource/Input/"
output_folder_path = "DataSource/Output/"

#### Game Title Process Method

In [19]:
def title_process (df):
    # remove everything in front of last column
    df['Game Title'] = df['Game Title'].str.replace(' : ', ':', regex = False).str.rsplit(':', n=1).str[-1].str.upper()

    # remove platform
    # pattern = '|'.join(platforms)
    # df['Game Title'] = df['Game Title'].str.replace(rf'\s*\b({pattern})\b.*', '', regex=True)
    
    return df

#### Item Code Process Method

In [5]:
def item_process (df):
    df['Item'] = df['Item'].apply(lambda x: '-'.join(x.split('-')[:2]))
    return df

# Sales

In [7]:
file_name = "old_Sales.xlsx"
sales_df = pd.read_excel('DataSource/Input/old_Sales.xlsx', skiprows=5)
#display(sales_df)
sales_df = sales_df[['Item', 'Qty. Sold', 'Sales (USD)', 'Month']]

sales_df = sales_df.rename(columns = {'Qty. Sold': 'Sales Units'})
sales_df = sales_df.rename(columns = {'Sales (USD)': 'Sales Amount'})
sales_df = sales_df[sales_df["Sales Units"] >= 0]

sales_df

                    Item  Sales Units  Sales Amount    Month
0     COC1-PS3-US-VG-DLC            3          2.07  2024-09
1     COC1-PS3-US-VG-PSN           11          7.65  2024-09
2         COC1-STM-PC-VG            6          7.51  2024-09
3      KAM1-NSW-EU-eshop           12        108.95  2024-09
4      KAM1-NSW-US-eshop           28        269.14  2024-09
...                  ...          ...           ...      ...
1042  FAL2-XB1-EU-VG-XBL            0          0.00  2024-09
1043  FAL2-XB1-US-VG-DLC            0          0.00  2024-09
1044  FAL2-XB1-US-VG-XBL            0          0.00  2024-09
1045   FAL2-XB1-WS-VG-SE            1         59.99  2024-09
1046                 NaN       219481    3682881.55      NaN

[1043 rows x 4 columns]

# Coop

In [8]:
file_name = "CustomGeneralLedgerwithAccountName_Division10_2025Jan2025Mar.xlsx"
custom_df = pd.read_excel(input_folder_path + file_name, skiprows=5)
title_process(custom_df)

,Account,Type,Date,Document Number,Name,Memo,Debit,Credit,Balance,Account: Name,Division: Name,Game Title: Name,Game Title,Item
0,Cash and Cash Equivalents,NaN,NaT,NaN,NaN,NaN,0.0,0.00,0.000000e+00,NaN,NaN,NaN,NaN,NaN
1,Cash and Cash Equivalents:BOW Checking (old),NaN,NaT,NaN,NaN,NaN,0.0,0.00,0.000000e+00,NaN,NaN,NaN,NaN,NaN
2,Cash and Cash Equivalents:BOW Checking-ACH Deb...,Check,2025-01-02,5418,BOW,Line of credit fee,NaN,500.00,-5.000000e+02,BOW Checking-ACH Debits only (xxxx3945),- No Division -,- No Game Title -,- NO GAME TITLE -,- No Item -
3,Cash and Cash Equivalents:BOW Checking-ACH Deb...,Customer Refund,2025-01-06,5430,Jeremy Coy,Backorder (85P53086V4553500D),NaN,121.25,-6.212500e+02,BOW Checking-ACH Debits only (xxxx3945),- No Division -,- No Game Title -,- NO GAME TITLE -,- No Item -
4,Cash and Cash Equivalents:BOW Checking-ACH Deb...,Check,2025-01-09,5458,Georgia Department of Revenue,NaN,NaN,100.91,-7.221600e+02,BOW Checking-ACH Debits only (xxxx3945),- No Division -,- No Game Title -,- NO GAME TITLE -,- No Item -
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99997,Sales:Sales-North America:Sales-Online Store:S...,Invoice,2025-02-10,NISINV-79398,Brett Schwartz,NaN,0.0,NaN,-5.282631e+06,Accounts Receivable: Online Store,NA Games-STORE,- No Game Title -,- NO GAME TITLE -,Free USPS Shipping (Priority Mail)
99998,Sales:Sales-North America:Sales-Online Store:S...,Invoice,2025-02-10,NISINV-80197,Imran Sher-Khan,NaN,0.0,NaN,-5.282631e+06,Accounts Receivable: Online Store,NA Games-STORE,- No Game Title -,- NO GAME TITLE -,Free USPS Shipping (Priority Mail)
99999,Sales:Sales-North America:Sales-Online Store:S...,Invoice,2025-02-10,NISINV-78783,Kevin Street,NaN,0.0,NaN,-5.282631e+06,Accounts Receivable: Online Store,NA Games-STORE,- No Game Title -,- NO GAME TITLE -,Free USPS Shipping (Priority Mail)
100000,Sales:Sales-North America:Sales-Online Store:S...,Invoice,2025-02-10,NISINV-79512,Sheridan Maxey,NaN,NaN,10.61,-5.282642e+06,Accounts Receivable: Online Store,NA Games-STORE,- No Game Title -,- NO GAME TITLE -,USPS Priority Mail® (Taxed)
100001,The results of this report are too large. Plea...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
coop_df = custom_df[custom_df["Item"] == "CO-OP AD Expense"]
coop_df = coop_df[['Game Title', 'Debit', 'Credit', 'Date']]
coop_df["Coop_expense"] = coop_df["Debit"].fillna(0) + coop_df["Credit"].fillna(0)
coop_df['Month'] = coop_df['Date'].dt.strftime('%Y-%m')
coop_df = coop_df[['Game Title', 'Coop_expense', 'Month']]


coop_df

                          Game Title  Coop_expense    Month
49849                  DISGAEA 7 NSW         35.18  2025-01
49850    TRAILS THROUGH DAYBREAK NSW        330.48  2025-01
49856  TRAILS THROUGH DAYBREAK 2 PS5      13023.36  2025-02
49857            PHANTOM BRAVE 2 NSW      12288.96  2025-02
49858    TRAILS THROUGH DAYBREAK PS5        844.56  2025-02
49859            PHANTOM BRAVE 2 PS5      10379.52  2025-02
49860            PHANTOM BRAVE 2 PS4       1058.76  2025-02
49861  TRAILS THROUGH DAYBREAK 2 NSW      10342.80  2025-02
49862                  DISGAEA 7 PS5        170.04  2025-02
49863  TRAILS THROUGH DAYBREAK 2 PS4       1530.00  2025-02
49864          CALIGULA EFFECT 2 PS5        170.17  2025-02
49865    TRAILS THROUGH DAYBREAK NSW        771.12  2025-02
49866    TRAILS THROUGH DAYBREAK PS4        146.88  2025-02
49867     PROCESS OF ELIMINATION PS4         13.60  2025-02
49868             RPG MAKER WITH PS5       3023.25  2025-03
49869  TRAILS THROUGH DAYBREAK 2 NSW       5810.32  2025-03
49870            PHANTOM BRAVE 2 NSW        367.20  2025-03
49871  TRAILS THROUGH DAYBREAK 2 PS4        673.20  2025-03
49872  TRAILS THROUGH DAYBREAK 2 PS5       8017.20  2025-03
49873             RPG MAKER WITH PS4        566.83  2025-03

# Paid PP

In [10]:
pp_df = custom_df[custom_df["Item"].notna() & custom_df["Item"].str.startswith("Mark Down-")]
pp_df = pp_df[['Game Title', 'Debit', 'Credit', 'Date']]
pp_df["Paid_PP"] = pp_df["Debit"].fillna(0) + pp_df["Credit"].fillna(0)
pp_df['Month'] = pp_df['Date'].dt.strftime('%Y-%m')
pp_df = pp_df[['Game Title', 'Paid_PP', 'Month']]
pp_df

                          Game Title  Paid_PP    Month
69689           VOID TERRARIUM 2 PS4   174.67  2025-02
69691    TRAILS THROUGH DAYBREAK NSW  4955.84  2025-02
69692                   REYNATIS PS4  5117.44  2025-02
69693    TRAILS THROUGH DAYBREAK PS5    26.93  2025-02
69694        LEGEND OF LEGACY HD PS4  5071.00  2025-02
...                              ...      ...      ...
69818  TRAILS THROUGH DAYBREAK 2 NSW   367.20  2025-03
69819             RPG MAKER WITH PS5  1243.13  2025-03
69820             RPG MAKER WITH PS4   234.08  2025-03
69821  TRAILS THROUGH DAYBREAK 2 PS5   367.20  2025-03
69822  TRAILS THROUGH DAYBREAK 2 PS4  2970.75  2025-03

[110 rows x 3 columns]

# COGS

In [11]:
cogs_df = custom_df[custom_df["Account: Name"].str.contains('Material Costs', na=False)]
cogs_df = cogs_df[['Game Title', 'Debit', 'Credit', 'Date']]
cogs_df['Month'] = cogs_df['Date'].dt.strftime('%Y-%m')
cogs_df["Material_COGS"] = cogs_df["Debit"].fillna(0) + cogs_df["Credit"].fillna(0)
cogs_df = cogs_df[['Game Title', 'Material_COGS', 'Month']]
cogs_df

                        Game Title  Material_COGS    Month
29045  TRAILS THROUGH DAYBREAK PS4           9.62  2025-01
30470              PHANTOM BRAVE 2          12.25  2025-01
30474    TRAILS THROUGH DAYBREAK 2          52.81  2025-01
30485              PHANTOM BRAVE 2          20.45  2025-01
30486              PHANTOM BRAVE 2          20.79  2025-01
30487             KIMI NI TODOKE 2        2254.82  2025-01
30515    TRAILS THROUGH DAYBREAK 2           3.22  2025-01
30543             KIMI NI TODOKE 3         190.00  2025-01
30545    TRAILS THROUGH DAYBREAK 2          20.36  2025-01
30547                      03-2024          22.49  2025-01
40189            ATELIER YUMIA XB1           0.00  2025-03
41025            ATELIER YUMIA PS5           0.00  2025-03
41366            ATELIER YUMIA XB1           0.00  2025-03
41595            ATELIER YUMIA NSW           0.00  2025-03
41664            ATELIER YUMIA PS5           0.00  2025-03
41913            ATELIER YUMIA NSW           0.00  2025-03

# Royalty

In [12]:
royalty_df = pd.read_excel(input_folder_path + "Royalty/Mar 2025 NISJ Royalty from Netsuite.xlsx", skiprows=4)
royalty_df = royalty_df[['Memo', 'Amount']]
royalty_df = royalty_df.rename(columns = {'Memo': 'Item'})
royalty_df = royalty_df.rename(columns = {'Amount': 'Royalty'})

royalty_df

                      Item  Royalty
0       ARC1-PS3-US-VG-PSN    20.53
1          CDU3-PS4-US-PSN   124.88
2       CGI2-PSV-US-VG-PSN    20.99
3       CGS2-PSV-US-VG-DLC    13.74
4       CGS2-PSV-US-VG-PSN    20.99
..                     ...      ...
192      YSD1-NSW-US-eshop  3451.23
193  YSD1-NSW-US-eshop-DLC   112.60
194     ZHP1-PSP-US-VG-DLC     0.34
195     ZHP1-PSP-US-VG-PSN     3.50
196                    NaN      NaN

[197 rows x 2 columns]

In [13]:
import os
royalty_df_list = []

for royalty_name in os.listdir(input_folder_path + "Royalty"):
    month, year, file_type = royalty_name.split(' ', 2)
    Month = f"{month} {year}"

    if file_type == "NISJ EUR Royalty from Netsuite.xlsx":
        royalty_df = pd.read_excel(input_folder_path + "Royalty/" + royalty_name, skiprows=0)
        royalty_df = royalty_df[['Memo', 'Amount (Debit)', 'Amount (Credit)']]
        royalty_df['Amount'] = royalty_df['Amount (Debit)'].fillna(0) + royalty_df['Amount (Credit)'].fillna(0)
    else:
        royalty_df = pd.read_excel(input_folder_path + "Royalty/" + royalty_name, skiprows=4)


    royalty_df = royalty_df[['Memo', 'Amount']]
    royalty_df = royalty_df.rename(columns = {'Memo': 'Item'})
    royalty_df = royalty_df.rename(columns = {'Amount': 'Royalty'})
    royalty_df['Month'] = pd.to_datetime(Month, format='%b %Y').strftime('%Y-%m')
    royalty_df_list.append(royalty_df)

royalty_df = pd.concat(royalty_df_list, ignore_index=True)
royalty_df

                             Item   Royalty    Month
0                             NaN  13059.69  2025-02
1             CDU3-PS4-EU-VG-PSNE     41.19  2025-02
2             CGI2-PSV-EU-VG-PSNE     23.29  2025-02
3              CGS2-PSV-EU-VG-DLC      8.14  2025-02
4             CGS2-PSV-EU-VG-PSNE     11.95  2025-02
...                           ...       ...      ...
1246    PBR2-PS5-US PSN Amourtize  15649.06  2025-03
1247  PBR2-NSW-EU-eshop Amourtize   5321.94  2025-03
1248    PBR2-PS4-EU PSN Amourtize    105.18  2025-03
1249    PBR2-PS5-EU PSN Amourtize   5198.98  2025-03
1250                      Actions       NaN  2025-03

[1251 rows x 3 columns]

# Contact

In [14]:
contract_df = pd.read_csv(input_folder_path + "Game Title with Contract Name.csv")
contract_df = contract_df.rename(columns={'game_title': 'Game Title', 'contract_name': 'Contract'})
contract_df = contract_df[['Game Title', 'Contract']]
contract_df = title_process(contract_df)
contract_df

                      Game Title            Contract
0           GIRAFFE & ANNIKA NSW  Giraffe and Annika
1           GIRAFFE & ANNIKA PS4  Giraffe and Annika
2             NEO ATLAS 1469 NSW  Giraffe and Annika
3                LA-MULANA 1 NSW       LA-MULANA 1&2
4                LA-MULANA 1 PS4       LA-MULANA 1&2
..                           ...                 ...
346  DENPA ONNA TO SEISHUN OTOKO                 TBS
347             ECCENTRIC FAMILY                 YTE
348             HANASAKU IROHA 1                 YTE
349             HANASAKU IROHA 2                 YTE
350         HANASAKU IROHA MOVIE                 YTE

[351 rows x 2 columns]

# Item Master List Merging

In [15]:
master_df = pd.read_excel(input_folder_path + "Item Master List.xlsx")

In [16]:
marginal_profit_df = master_df[["Inactive", "Game Title", "Name", "Platform", "Division", 'Game Type']].copy()
marginal_profit_df = marginal_profit_df[marginal_profit_df["Inactive"] == "No" ]
marginal_profit_df["Title"] = master_df["Game Title"]
marginal_profit_df = marginal_profit_df[["Title", "Game Title", "Name",  "Platform", "Division", 'Game Type']]
marginal_profit_df = marginal_profit_df.rename(columns = {'Name': 'Item'})
title_process(marginal_profit_df)

marginal_profit_df = marginal_profit_df.merge(sales_df, on = "Item", how = "left")
marginal_profit_df = marginal_profit_df.merge(coop_df, on = ["Game Title","Month"], how = "left")
marginal_profit_df = marginal_profit_df.merge(pp_df, on = ["Game Title","Month"], how = "left")
marginal_profit_df = marginal_profit_df.merge(cogs_df, on = ["Game Title","Month"], how = "left")
marginal_profit_df = marginal_profit_df.merge(royalty_df, on = ["Item","Month"], how = "left")
marginal_profit_df = marginal_profit_df.merge(contract_df, on = ["Game Title"], how = "left")


marginal_profit_df["Marginal Profit"] = (
    marginal_profit_df["Sales Amount"].fillna(0) -
    marginal_profit_df["Paid_PP"].fillna(0) -
    marginal_profit_df["Coop_expense"].fillna(0) -
    marginal_profit_df["Material_COGS"].fillna(0) -
    marginal_profit_df["Royalty"].fillna(0)
)

marginal_profit_df = marginal_profit_df.drop(columns = ["Game Title"])
marginal_profit_df = marginal_profit_df.assign(**{'Game Type': marginal_profit_df.pop('Game Type')})
marginal_profit_df = marginal_profit_df.assign(**{'Contract': marginal_profit_df.pop('Contract')})

marginal_profit_df

,Title,Item,Platform,Division,Sales Units,Sales Amount,Month,Coop_expense,Paid_PP,Material_COGS,Royalty,Marginal Profit,Game Type,Contract
0,03-2025 : Ys 10 : Ys 10 PS5,YSN1-PS5-EU-VGN-DX-DE,PS5,EU Games,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,Physical,Ys 10
1,03-2025 : Ys 10 : Ys 10 PS5,YSN1-PS5-EU-VGN-DX,PS5,EU Games,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,Physical,Ys 10
2,03-2024 : Ys IX Monstrum Nox : Ys IX Monstrum ...,YSM1-PS5-EU-VGN-DX-DE,PS5,EU Games,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,Physical,Ys 9 PS5
3,03-2024 : Ys IX Monstrum Nox : Ys IX Monstrum ...,YSM1-PS5-EU-VGN-DX,PS5,EU Games,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,Physical,Ys 9 PS5
4,03-2026 : Trails beyond the Horizon : Trails b...,TBH1-NSW-EU-CART,NSW,EU Games,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,Components,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11102,Goods,W03PR-GP001,NaN,NA Games : NA Games-STORE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Ys Anniversary
11103,Goods,W03PR-GP001,NaN,NA Games : NA Games-STORE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Trails through Daybreak - Goods
11104,Goods,W03PR-GP001,NaN,NA Games : NA Games-STORE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Ys 10 - Goods
11105,Goods,W03PR-GP001,NaN,NA Games : NA Games-STORE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Trails through Daybreak 2 - Goods
11106,Goods,W03PR-GP001,NaN,NA Games : NA Games-STORE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,REYNATIS Goods

Export to csv

In [17]:
marginal_profit_df.to_csv(output_folder_path + 'marginal_profit_report.csv')