In [38]:
# !pip install openpyxl

In [39]:
# Libraries
import pandas as pd
input_folder_path = "DataSource/Input/"
output_folder_path = "DataSource/Output/"

#### Game Title Process Method

In [40]:
def title_process (df):
    # remove everything in front of last column
    df['Game Title'] = df['Game Title'].str.replace(' : ', ':', regex = False).str.rsplit(':', n=1).str[-1].str.upper()

    # remove platform
    # pattern = '|'.join(platforms)
    # df['Game Title'] = df['Game Title'].str.replace(rf'\s*\b({pattern})\b.*', '', regex=True)
    
    return df

#### Item Code Process Method

In [41]:
def item_process (df):
    df['Item'] = df['Item'].apply(lambda x: '-'.join(x.split('-')[:2]))
    return df

Sales Process

In [42]:
file_name = "SalesbyItembyLicensor-ForRoyaltyCal(Acc)new_Jan2025March2025_0707.xlsx"
sales_df = pd.read_excel(input_folder_path + file_name, skiprows=5)
#display(sales_df)
sales_df = sales_df[['Item', 'Qty. Sold', 'Sales (USD)']]

sales_df = sales_df.rename(columns = {'Qty. Sold': 'Sales Units'})
sales_df = sales_df.rename(columns = {'Sales (USD)': 'Sales Amount'})
sales_df = sales_df[sales_df["Sales Units"] >= 0]

sales_df

                    Item  Sales Units  Sales Amount
0     COC1-PS3-US-VG-DLC           16         11.52
1     COC1-PS3-US-VG-DLC           24         16.56
2     COC1-PS3-US-VG-PSN            9          6.27
3     COC1-PS3-US-VG-PSN            9          6.21
4     COC1-PS3-US-VG-PSN           24         16.64
...                  ...          ...           ...
3355  FAL2-XB1-US-VG-XBL           45        366.39
3356  FAL2-XB1-US-VG-XBL           12        120.84
3357           Setup Fee            1        125.00
3358           Setup Fee            4        500.00
3359                 NaN       545823    8260750.07

[3315 rows x 3 columns]

Coop

In [43]:
file_name = "CustomGeneralLedgerwithAccountName_Division10_2025Jan2025Mar.xlsx"
custom_df = pd.read_excel(input_folder_path + file_name, skiprows=5)
title_process(custom_df)

,Account,Type,Date,Document Number,Name,Memo,Debit,Credit,Balance,Account: Name,Division: Name,Game Title: Name,Game Title,Item
0,Cash and Cash Equivalents,NaN,NaT,NaN,NaN,NaN,0.0,0.00,0.000000e+00,NaN,NaN,NaN,NaN,NaN
1,Cash and Cash Equivalents:BOW Checking (old),NaN,NaT,NaN,NaN,NaN,0.0,0.00,0.000000e+00,NaN,NaN,NaN,NaN,NaN
2,Cash and Cash Equivalents:BOW Checking-ACH Deb...,Check,2025-01-02,5418,BOW,Line of credit fee,NaN,500.00,-5.000000e+02,BOW Checking-ACH Debits only (xxxx3945),- No Division -,- No Game Title -,- NO GAME TITLE -,- No Item -
3,Cash and Cash Equivalents:BOW Checking-ACH Deb...,Customer Refund,2025-01-06,5430,Jeremy Coy,Backorder (85P53086V4553500D),NaN,121.25,-6.212500e+02,BOW Checking-ACH Debits only (xxxx3945),- No Division -,- No Game Title -,- NO GAME TITLE -,- No Item -
4,Cash and Cash Equivalents:BOW Checking-ACH Deb...,Check,2025-01-09,5458,Georgia Department of Revenue,NaN,NaN,100.91,-7.221600e+02,BOW Checking-ACH Debits only (xxxx3945),- No Division -,- No Game Title -,- NO GAME TITLE -,- No Item -
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99997,Sales:Sales-North America:Sales-Online Store:S...,Invoice,2025-02-10,NISINV-79398,Brett Schwartz,NaN,0.0,NaN,-5.282631e+06,Accounts Receivable: Online Store,NA Games-STORE,- No Game Title -,- NO GAME TITLE -,Free USPS Shipping (Priority Mail)
99998,Sales:Sales-North America:Sales-Online Store:S...,Invoice,2025-02-10,NISINV-80197,Imran Sher-Khan,NaN,0.0,NaN,-5.282631e+06,Accounts Receivable: Online Store,NA Games-STORE,- No Game Title -,- NO GAME TITLE -,Free USPS Shipping (Priority Mail)
99999,Sales:Sales-North America:Sales-Online Store:S...,Invoice,2025-02-10,NISINV-78783,Kevin Street,NaN,0.0,NaN,-5.282631e+06,Accounts Receivable: Online Store,NA Games-STORE,- No Game Title -,- NO GAME TITLE -,Free USPS Shipping (Priority Mail)
100000,Sales:Sales-North America:Sales-Online Store:S...,Invoice,2025-02-10,NISINV-79512,Sheridan Maxey,NaN,NaN,10.61,-5.282642e+06,Accounts Receivable: Online Store,NA Games-STORE,- No Game Title -,- NO GAME TITLE -,USPS Priority Mail® (Taxed)
100001,The results of this report are too large. Plea...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [44]:
coop_df = custom_df[custom_df["Item"] == "CO-OP AD Expense"]
coop_df = coop_df[['Game Title', 'Debit', 'Credit']]
coop_df["Coop_expense"] = coop_df["Debit"].fillna(0) + coop_df["Credit"].fillna(0)
coop_df = coop_df[['Game Title', 'Coop_expense']]

coop_df

                          Game Title  Coop_expense
49849                  DISGAEA 7 NSW         35.18
49850    TRAILS THROUGH DAYBREAK NSW        330.48
49856  TRAILS THROUGH DAYBREAK 2 PS5      13023.36
49857            PHANTOM BRAVE 2 NSW      12288.96
49858    TRAILS THROUGH DAYBREAK PS5        844.56
49859            PHANTOM BRAVE 2 PS5      10379.52
49860            PHANTOM BRAVE 2 PS4       1058.76
49861  TRAILS THROUGH DAYBREAK 2 NSW      10342.80
49862                  DISGAEA 7 PS5        170.04
49863  TRAILS THROUGH DAYBREAK 2 PS4       1530.00
49864          CALIGULA EFFECT 2 PS5        170.17
49865    TRAILS THROUGH DAYBREAK NSW        771.12
49866    TRAILS THROUGH DAYBREAK PS4        146.88
49867     PROCESS OF ELIMINATION PS4         13.60
49868             RPG MAKER WITH PS5       3023.25
49869  TRAILS THROUGH DAYBREAK 2 NSW       5810.32
49870            PHANTOM BRAVE 2 NSW        367.20
49871  TRAILS THROUGH DAYBREAK 2 PS4        673.20
49872  TRAILS THROUGH DAYBREAK 2 PS5       8017.20
49873             RPG MAKER WITH PS4        566.83

Paid PP

In [45]:
pp_df = custom_df[custom_df["Item"].notna() & custom_df["Item"].str.startswith("Mark Down-")]
pp_df = pp_df[['Game Title', 'Debit', 'Credit']]
pp_df["Paid_PP"] = pp_df["Debit"].fillna(0) + pp_df["Credit"].fillna(0)
pp_df = pp_df[['Game Title', 'Paid_PP']]
pp_df

                          Game Title  Paid_PP
69689           VOID TERRARIUM 2 PS4   174.67
69691    TRAILS THROUGH DAYBREAK NSW  4955.84
69692                   REYNATIS PS4  5117.44
69693    TRAILS THROUGH DAYBREAK PS5    26.93
69694        LEGEND OF LEGACY HD PS4  5071.00
...                              ...      ...
69818  TRAILS THROUGH DAYBREAK 2 NSW   367.20
69819             RPG MAKER WITH PS5  1243.13
69820             RPG MAKER WITH PS4   234.08
69821  TRAILS THROUGH DAYBREAK 2 PS5   367.20
69822  TRAILS THROUGH DAYBREAK 2 PS4  2970.75

[110 rows x 2 columns]

COGS

In [46]:
cogs_df = custom_df[custom_df["Account: Name"].str.contains('Material Costs', na=False)]
cogs_df = cogs_df[['Game Title', 'Debit', 'Credit']]
cogs_df["Material_COGS"] = cogs_df["Debit"].fillna(0) + cogs_df["Credit"].fillna(0)
cogs_df = cogs_df[['Game Title', 'Material_COGS']]
cogs_df

                        Game Title  Material_COGS
29045  TRAILS THROUGH DAYBREAK PS4           9.62
30470              PHANTOM BRAVE 2          12.25
30474    TRAILS THROUGH DAYBREAK 2          52.81
30485              PHANTOM BRAVE 2          20.45
30486              PHANTOM BRAVE 2          20.79
30487             KIMI NI TODOKE 2        2254.82
30515    TRAILS THROUGH DAYBREAK 2           3.22
30543             KIMI NI TODOKE 3         190.00
30545    TRAILS THROUGH DAYBREAK 2          20.36
30547                      03-2024          22.49
40189            ATELIER YUMIA XB1           0.00
41025            ATELIER YUMIA PS5           0.00
41366            ATELIER YUMIA XB1           0.00
41595            ATELIER YUMIA NSW           0.00
41664            ATELIER YUMIA PS5           0.00
41913            ATELIER YUMIA NSW           0.00

Royalty

In [47]:
royalty_df = pd.read_excel(input_folder_path + "Royalty/Mar 2025 NISJ Royalty from Netsuite.xlsx", skiprows=4)
royalty_df = royalty_df[['Memo', 'Amount']]
royalty_df = royalty_df.rename(columns = {'Memo': 'Item'})
royalty_df = royalty_df.rename(columns = {'Amount': 'Royalty'})

royalty_df

                      Item  Royalty
0       ARC1-PS3-US-VG-PSN    20.53
1          CDU3-PS4-US-PSN   124.88
2       CGI2-PSV-US-VG-PSN    20.99
3       CGS2-PSV-US-VG-DLC    13.74
4       CGS2-PSV-US-VG-PSN    20.99
..                     ...      ...
192      YSD1-NSW-US-eshop  3451.23
193  YSD1-NSW-US-eshop-DLC   112.60
194     ZHP1-PSP-US-VG-DLC     0.34
195     ZHP1-PSP-US-VG-PSN     3.50
196                    NaN      NaN

[197 rows x 2 columns]

Item Master List Merging

In [48]:
master_df = pd.read_excel(input_folder_path + "Item Master List.xlsx")

In [49]:
marginal_profit_df = master_df[["Game Title", "Name", "Platform", "Division"]].copy()
marginal_profit_df["Title"] = master_df["Game Title"]
marginal_profit_df = marginal_profit_df[["Title", "Game Title", "Name", "Platform", "Division"]]
marginal_profit_df = marginal_profit_df.rename(columns = {'Name': 'Item'})
title_process(marginal_profit_df)

marginal_profit_df = marginal_profit_df.merge(sales_df, on = "Item", how = "left")
marginal_profit_df = marginal_profit_df.merge(coop_df, on = "Game Title", how = "left")
marginal_profit_df = marginal_profit_df.merge(pp_df, on = "Game Title", how = "left")
marginal_profit_df = marginal_profit_df.merge(cogs_df, on = "Game Title", how = "left")
marginal_profit_df = marginal_profit_df.merge(royalty_df, on = "Item", how = "left")

marginal_profit_df["Marginal Profit"] = (
    marginal_profit_df["Sales Amount"].fillna(0) -
    marginal_profit_df["Paid_PP"].fillna(0) -
    marginal_profit_df["Coop_expense"].fillna(0) -
    marginal_profit_df["Material_COGS"].fillna(0) -
    marginal_profit_df["Royalty"].fillna(0)
)

marginal_profit_df = marginal_profit_df.drop(columns = ["Game Title"])

marginal_profit_df

,Title,Item,Platform,Division,Sales Units,Sales Amount,Coop_expense,Paid_PP,Material_COGS,Royalty,Marginal Profit
0,03-2025 : Ys 10 : Ys 10 PS5,YSN1-PS5-EU-VGN-DX-DE,PS5,EU Games,NaN,NaN,NaN,4955.85,NaN,NaN,-4955.85
1,03-2025 : Ys 10 : Ys 10 PS5,YSN1-PS5-EU-VGN-DX,PS5,EU Games,NaN,NaN,NaN,4955.85,NaN,NaN,-4955.85
2,03-2024 : Ys IX Monstrum Nox : Ys IX Monstrum ...,YSM1-PS5-EU-VGN-DX-DE,PS5,EU Games,NaN,NaN,NaN,NaN,NaN,NaN,0.00
3,03-2024 : Ys IX Monstrum Nox : Ys IX Monstrum ...,YSM1-PS5-EU-VGN-DX,PS5,EU Games,NaN,NaN,NaN,NaN,NaN,NaN,0.00
4,03-2026 : Trails beyond the Horizon : Trails b...,TBH1-NSW-EU-CART,NSW,EU Games,NaN,NaN,NaN,NaN,NaN,NaN,0.00
...,...,...,...,...,...,...,...,...,...,...,...
12994,My Lord!? : My Lord!? 1 PSP-EU,BAD1-PSP-IT-VG,NaN,EU Games,NaN,NaN,NaN,NaN,NaN,NaN,0.00
12995,My Lord!? : My Lord!? 1 PSP-EU,BAD1-PSP-DE-VG,NaN,EU Games,NaN,NaN,NaN,NaN,NaN,NaN,0.00
12996,My Lord!? : My Lord!? 1 PSP-EU,BAD1-PSP-FR-VG,NaN,EU Games,NaN,NaN,NaN,NaN,NaN,NaN,0.00
12997,My Lord!? : My Lord!? 1 PSP-EU,BAD1-PSP-AU-VG,NaN,EU Games,NaN,NaN,NaN,NaN,NaN,NaN,0.00
12998,NaN,TEST ITEM #1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00

Export to csv

In [50]:
marginal_profit_df.to_csv(output_folder_path + 'marginal_profit_report.csv')