# Required Library

In [ ]:
# !pip install openpyxl

In [ ]:
# Libraries
import pandas as pd
input_folder_path = "DataSource/Input/"
output_folder_path = "DataSource/Output/"

#### Game Title Process Method

In [ ]:
def title_process (df):
    # remove everything in front of last column
    df['Game Title'] = df['Game Title'].str.replace(' : ', ':', regex = False).str.rsplit(':', n=1).str[-1].str.upper()

    # remove platform
    # pattern = '|'.join(platforms)
    # df['Game Title'] = df['Game Title'].str.replace(rf'\s*\b({pattern})\b.*', '', regex=True)
    
    return df

#### Item Code Process Method

In [ ]:
def item_process (df):
    df['Item'] = df['Item'].apply(lambda x: '-'.join(x.split('-')[:2]))
    return df

# Sales

In [ ]:
file_name = "SalesbyItembyLicensor-ForRoyaltyCal(Acc)new_Jan2025March2025_0707.xlsx"
sales_df = pd.read_excel(input_folder_path + file_name, skiprows=5)
#display(sales_df)
sales_df = sales_df[['Item', 'Qty. Sold', 'Sales (USD)', 'Month']]

sales_df = sales_df.rename(columns = {'Qty. Sold': 'Sales Units'})
sales_df = sales_df.rename(columns = {'Sales (USD)': 'Sales Amount'})
sales_df = sales_df[sales_df["Sales Units"] >= 0]

sales_df

# Coop

In [ ]:
file_name = "CustomGeneralLedgerwithAccountName_Division10_2025Jan2025Mar.xlsx"
custom_df = pd.read_excel(input_folder_path + file_name, skiprows=5)
title_process(custom_df)

In [ ]:
coop_df = custom_df[custom_df["Item"] == "CO-OP AD Expense"]
coop_df = coop_df[['Game Title', 'Debit', 'Credit', 'Date']]
coop_df["Coop_expense"] = coop_df["Debit"].fillna(0) + coop_df["Credit"].fillna(0)
coop_df['Month'] = coop_df['Date'].dt.strftime('%Y-%m')
coop_df = coop_df[['Game Title', 'Coop_expense', 'Month']]


coop_df

# Paid PP

In [ ]:
pp_df = custom_df[custom_df["Item"].notna() & custom_df["Item"].str.startswith("Mark Down-")]
pp_df = pp_df[['Game Title', 'Debit', 'Credit', 'Date']]
pp_df["Paid_PP"] = pp_df["Debit"].fillna(0) + pp_df["Credit"].fillna(0)
pp_df['Month'] = pp_df['Date'].dt.strftime('%Y-%m')
pp_df = pp_df[['Game Title', 'Paid_PP', 'Month']]
pp_df

# COGS

In [ ]:
cogs_df = custom_df[custom_df["Account: Name"].str.contains('Material Costs', na=False)]
cogs_df = cogs_df[['Game Title', 'Debit', 'Credit', 'Date']]
cogs_df['Month'] = cogs_df['Date'].dt.strftime('%Y-%m')
cogs_df["Material_COGS"] = cogs_df["Debit"].fillna(0) + cogs_df["Credit"].fillna(0)
cogs_df = cogs_df[['Game Title', 'Material_COGS', 'Month']]
cogs_df

# Royalty

In [ ]:
royalty_df = pd.read_excel(input_folder_path + "Royalty/Mar 2025 NISJ Royalty from Netsuite.xlsx", skiprows=4)
royalty_df = royalty_df[['Memo', 'Amount']]
royalty_df = royalty_df.rename(columns = {'Memo': 'Item'})
royalty_df = royalty_df.rename(columns = {'Amount': 'Royalty'})

royalty_df

In [ ]:
import os
royalty_df_list = []

for royalty_name in os.listdir(input_folder_path + "Royalty"):
    month, year, file_type = royalty_name.split(' ', 2)
    Month = f"{month} {year}"

    if file_type == "NISJ EUR Royalty from Netsuite.xlsx":
        royalty_df = pd.read_excel(input_folder_path + "Royalty/" + royalty_name, skiprows=0)
        royalty_df = royalty_df[['Memo', 'Amount (Debit)', 'Amount (Credit)']]
        royalty_df['Amount'] = royalty_df['Amount (Debit)'].fillna(0) + royalty_df['Amount (Credit)'].fillna(0)
    else:
        royalty_df = pd.read_excel(input_folder_path + "Royalty/" + royalty_name, skiprows=4)


    royalty_df = royalty_df[['Memo', 'Amount']]
    royalty_df = royalty_df.rename(columns = {'Memo': 'Item'})
    royalty_df = royalty_df.rename(columns = {'Amount': 'Royalty'})
    royalty_df['Month'] = pd.to_datetime(Month, format='%b %Y').strftime('%Y-%m')
    royalty_df_list.append(royalty_df)

royalty_df = pd.concat(royalty_df_list, ignore_index=True)
royalty_df

# Contact

In [21]:
contract_df = pd.read_csv(input_folder_path + "Game Title with Contract Name.csv")
contract_df = contract_df.rename(columns={'game_title': 'Game Title', 'contract_name': 'Contract'})
contract_df = contract_df[['Game Title', 'Contract']]
contract_df = title_process(contract_df)
contract_df

                      Game Title            Contract
0           GIRAFFE & ANNIKA NSW  Giraffe and Annika
1           GIRAFFE & ANNIKA PS4  Giraffe and Annika
2             NEO ATLAS 1469 NSW  Giraffe and Annika
3                LA-MULANA 1 NSW       LA-MULANA 1&2
4                LA-MULANA 1 PS4       LA-MULANA 1&2
..                           ...                 ...
346  DENPA ONNA TO SEISHUN OTOKO                 TBS
347             ECCENTRIC FAMILY                 YTE
348             HANASAKU IROHA 1                 YTE
349             HANASAKU IROHA 2                 YTE
350         HANASAKU IROHA MOVIE                 YTE

[351 rows x 2 columns]

# Item Master List Merging

In [22]:
master_df = pd.read_excel(input_folder_path + "Item Master List.xlsx")

In [25]:
marginal_profit_df = master_df[["Inactive", "Game Title", "Name", "Platform", "Division", 'Game Type']].copy()
marginal_profit_df = marginal_profit_df[marginal_profit_df["Inactive"] == "No" ]
marginal_profit_df["Title"] = master_df["Game Title"]
marginal_profit_df = marginal_profit_df[["Title", "Game Title", "Name",  "Platform", "Division", 'Game Type']]
marginal_profit_df = marginal_profit_df.rename(columns = {'Name': 'Item'})
title_process(marginal_profit_df)

marginal_profit_df = marginal_profit_df.merge(sales_df, on = "Item", how = "left")
marginal_profit_df = marginal_profit_df.merge(coop_df, on = ["Game Title","Month"], how = "left")
marginal_profit_df = marginal_profit_df.merge(pp_df, on = ["Game Title","Month"], how = "left")
marginal_profit_df = marginal_profit_df.merge(cogs_df, on = ["Game Title","Month"], how = "left")
marginal_profit_df = marginal_profit_df.merge(royalty_df, on = ["Item","Month"], how = "left")
marginal_profit_df = marginal_profit_df.merge(contract_df, on = ["Game Title"], how = "left")


marginal_profit_df["Marginal Profit"] = (
    marginal_profit_df["Sales Amount"].fillna(0) -
    marginal_profit_df["Paid_PP"].fillna(0) -
    marginal_profit_df["Coop_expense"].fillna(0) -
    marginal_profit_df["Material_COGS"].fillna(0) -
    marginal_profit_df["Royalty"].fillna(0)
)

marginal_profit_df = marginal_profit_df.drop(columns = ["Game Title"])
marginal_profit_df = marginal_profit_df.assign(**{'Game Type': marginal_profit_df.pop('Game Type')})
marginal_profit_df = marginal_profit_df.assign(**{'Contract': marginal_profit_df.pop('Contract')})

marginal_profit_df

,Title,Item,Platform,Division,Sales Units,Sales Amount,Month,Coop_expense,Paid_PP,Material_COGS,Royalty,Marginal Profit,Game Type,Contract
0,03-2025 : Ys 10 : Ys 10 PS5,YSN1-PS5-EU-VGN-DX-DE,PS5,EU Games,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,Physical,Ys 10
1,03-2025 : Ys 10 : Ys 10 PS5,YSN1-PS5-EU-VGN-DX,PS5,EU Games,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,Physical,Ys 10
2,03-2024 : Ys IX Monstrum Nox : Ys IX Monstrum ...,YSM1-PS5-EU-VGN-DX-DE,PS5,EU Games,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,Physical,Ys 9 PS5
3,03-2024 : Ys IX Monstrum Nox : Ys IX Monstrum ...,YSM1-PS5-EU-VGN-DX,PS5,EU Games,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,Physical,Ys 9 PS5
4,03-2026 : Trails beyond the Horizon : Trails b...,TBH1-NSW-EU-CART,NSW,EU Games,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,Components,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13871,Goods,W03PR-GP001,NaN,NA Games : NA Games-STORE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Ys Anniversary
13872,Goods,W03PR-GP001,NaN,NA Games : NA Games-STORE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Trails through Daybreak - Goods
13873,Goods,W03PR-GP001,NaN,NA Games : NA Games-STORE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Ys 10 - Goods
13874,Goods,W03PR-GP001,NaN,NA Games : NA Games-STORE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Trails through Daybreak 2 - Goods
13875,Goods,W03PR-GP001,NaN,NA Games : NA Games-STORE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,REYNATIS Goods

Export to csv

In [26]:
marginal_profit_df.to_csv(output_folder_path + 'marginal_profit_report.csv')